Fix pull requests checklist reference
cookiecutter/cookiecutter pull request #1537
Opened 2021-04-26 22:01 UTC by glumia

The previous link was broken since the file was removed from github
gists. Its content was recovered with Internet Archive's Wayback Machine
and adapted to our specific context (eg. references to specific
platforms were removed since we already have tests for that on our CI).

Closes #1528

2021-04-26 22:32 UTC, simobasso commented
@glumia, thanks for this pull request!

As I said in https://github.com/cookiecutter/cookiecutter/pull/1529#discussion_r618709324, we should await the permission of @audreyfeldroy to use her gist in this project.

2021-04-27 00:43 UTC, insspb requested changes
This should not be merged in the way as it exist in this PR. 

1. You can extend CONTRIBUTING.md. Many things from PR_CHECKLIST already there.
2. Stop creating docs files in root folder of project. We should thing about removing most of them from there. No need to create more problems. for example HISTORY.md outdated and should be moved to docs for archive purposes only.

2021-04-27 00:45 UTC, insspb commented
@glumia Thank you for contribution. Unfortunately I do not think it can be merged as it is. I described problem in review comment.

2021-04-27 07:41 UTC, glumia commented
> @glumia, thanks for this pull request!
> 
> As I said in [#1529 (comment)](https://github.com/cookiecutter/cookiecutter/pull/1529#discussion_r618709324), we should await the permission of @audreyfeldroy to use her gist in this project.

Of course!

> This should not be merged in the way ...

Hmm okay, I was also not very sure about adding another file to project's root directory. I'll try to fit the contents of `PR_CHECKLIST.md` into `CONTRIBUTING.md`, hoping that it doesn't become too big.

2021-05-05 08:50 UTC, simobasso approved these changes

2021-05-05 08:56 UTC, merged

2021-05-05 08:56 UTC, simobasso commented
@glumia, thanks for the update 🙏 .