Release preparation for 2.0.1rc1
cookiecutter/cookiecutter pull request #1608
Opened 2021-10-30 17:19 UTC by audreyfeldroy

This PR includes all changes by @audreyfeldroy and @pydanny in preparation for releasing 2.0.1 Release Candidate 1.

2021-11-06 13:14 UTC, michaeljoseph requested changes

2021-11-06 13:14 UTC, michaeljoseph commented on CONTRIBUTING.md
> +Will run py.test with the python3.7 and python3.8 interpreters, for example.
```suggestion
This will run `py.test` with the `python3.7` and `python3.8` interpreters.
```

2021-11-10 17:21 UTC, ozer619 approved these changes
I helped @audreyfeldroy fix this and ran it locally to verify that it works with Tox.

2021-11-10 17:50 UTC, michaeljoseph approved these changes

2021-12-05 04:32 UTC, merged