Prompt with replay file
cookiecutter/cookiecutter pull request #1758
Opened 2022-08-04 16:42 UTC by w1ndblow

if replayfile have not all answers relatively cookiecutter config file it'll execute prompt operation

2022-10-18 22:49 UTC, w1ndblow commented
hi, @audreyfeldroy, @browniebroke, @ericof, @hackebrot, @insspb, @pydanny, @simobasso, @ssbarnea could you take a look my PR, please

2023-06-10 15:57 UTC, kurtmckee requested changes
@w1ndblow Thanks for your work on this.

Would you add tests that demonstrate that this feature is working as expected?

2023-06-10 15:57 UTC, kurtmckee commented on test_requirements.txt
> +defer
Where is this used?

2023-06-20 19:05 UTC, w1ndblow commented on test_requirements.txt
> +defer
missclick

2023-06-20 19:08 UTC, w1ndblow commented
i added one test, i can add more if needed

2023-07-07 17:24 UTC, w1ndblow commented
hi, could any one merge it? i merged this with main 3 times already :)

2023-07-07 21:01 UTC, ericof approved these changes

2023-07-11 15:19 UTC, merged