fixed failing lint ci action by updating repo of flake8
cookiecutter/cookiecutter pull request #1838
Opened 2023-05-05 16:26 UTC by Tamronimus

Hi

I think this update of the repository for the pre-commit-check will fix the lint step.

2023-05-05 23:56 UTC, mariovagomarzal approved these changes

2023-05-10 23:02 UTC, hashem-nowruzi requested changes
It is better not to change the version.
Update the version in another pull request.
Because the entire cookiecutter repository is done with version 4.0.1.
If we bump the version suddenly, we may encounter more errors.

2023-05-12 01:40 UTC, hashem-nowruzi approved these changes

2023-05-12 01:42 UTC, hashem-nowruzi approved these changes

2023-06-06 12:02 UTC, kurtmckee approved these changes
@audreyfeldroy, @jensens, @tmeckel 

Please merge this PR to resolve current lint failures.

2023-06-09 10:21 UTC, jensens approved these changes

2023-06-09 10:21 UTC, merged