Add jinja env docs
cookiecutter/cookiecutter pull request #1872
Opened 2023-06-27 23:28 UTC by pamelafox

This PR documents _jinja2_env_vars, which was added in 2020.

CC @kjaymiller who just used it in a project

2023-06-29 12:34 UTC, kurtmckee requested changes
Thanks so much for this work! I've requested a change to the Jinja documentation, but otherwise this looks good to me!

@pydanny @jensens @ericof Please merge this PR after the Jinja documentation link is updated. Thanks!

2023-06-29 12:34 UTC, kurtmckee commented on docs/advanced/jinja_env.rst
> +to customize the [Jinja2 environment](https://jinja.palletsprojects.com/en/3.0.x/api/?highlight=lstrip_blocks#jinja2.Environment).
The current link will highlight `lstrip_blocks` on the page, and 3.1 is the current Jinja version. Please use this instead:

```suggestion
to customize the [Jinja2 environment](https://jinja.palletsprojects.com/en/3.1.x/api/#jinja2.Environment).
```

2023-06-29 18:14 UTC, kurtmckee approved these changes

2023-06-29 20:52 UTC, pamelafox commented
Ah I bet the checks failed due to GitHub outage this morning, as they passed previously.

2023-07-01 14:25 UTC, ericof approved these changes

2023-07-01 14:25 UTC, merged